include: []
networks:
  pwn-flag-shop-network:
    driver: bridge
  pwn-lionexchange-1-network:
    driver: bridge
  pwn-lionexchange-2-network:
    driver: bridge
  pwn-msl-maingate-network:
    driver: bridge
  pwn-msl-secretvault-network:
    driver: bridge
  web-the-shadow-terminal-network:
    driver: bridge
  web-timecapsule-network:
    driver: bridge
services:
  pwn-flag-shop-flag-shop:
    build: challenges/pwn/Flag Shop/service\flag-shop
    container_name: pwn-flag-shop-flag-shop
    networks:
    - pwn-flag-shop-network
    ports:
    - 30003:10000
    restart: always
  pwn-lionexchange-1-lionexchange1:
    build: challenges/pwn/LionExchange 1/service\lionexchange1
    container_name: pwn-lionexchange-1-lionexchange1
    networks:
    - pwn-lionexchange-1-network
    ports:
    - 30001:2403
    restart: always
  pwn-lionexchange-2-lionexchange2:
    build: challenges/pwn/LionExchange 2/service\lionexchange2
    container_name: pwn-lionexchange-2-lionexchange2
    networks:
    - pwn-lionexchange-2-network
    ports:
    - 30000:2404
    restart: always
  pwn-msl-maingate-msl-level1:
    build: challenges/pwn/MSL-MainGate/service\level-one-service
    container_name: pwn-msl-maingate-msl-level1
    networks:
    - pwn-msl-maingate-network
    ports:
    - 30004:10000
    restart: always
  pwn-msl-secretvault-msl-level2:
    build: challenges/pwn/MSL-SecretVault/service\level-two
    container_name: pwn-msl-secretvault-msl-level2
    networks:
    - pwn-msl-secretvault-network
    ports:
    - 30002:10000
    restart: always
  web-the-shadow-terminal-shadow-terminal:
    build: challenges/web/The Shadow Terminal/service\src
    container_name: web-the-shadow-terminal-shadow-terminal
    networks:
    - web-the-shadow-terminal-network
    ports:
    - 31001:80
    restart: always
  web-timecapsule-time-capsule:
    build: challenges/web/TimeCapsule/service\
    container_name: web-timecapsule-time-capsule
    networks:
    - web-timecapsule-network
    ports:
    - 31000:31000
    restart: always
