name: Generate build scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install ctf-architect
        run: pip install git+https://github.com/DakshRocks21/CTF-Architect

      - name: Remove old files
        run: rm -f compose.yml port_mapping.yaml

      - name: Generate port_mapping.yaml using module
        run: python -m ctf_architect.cli repo mapping generate --yes

      - name: Generate compose.yml using module
        run: python -m ctf_architect.cli repo compose generate --force

      - name: Update stats
        run: python -m ctf_architect.cli repo stats update

      - name: Commit generated compose.yml
        uses: EndBug/add-and-commit@v9
        with:
          add: "compose.yml"
          message: "chore: update compose.yml and port_mapping.yml"
          author_name: "CTF Architect Updater"
          author_email: "85815311+DakshRocks21@users.noreply.github.com"
